name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: .github/workflows/reusable_workflows.yaml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: .github/workflows/reusable_workflows.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
