name: Greeting on variable day
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      - name: "Print environment stuff"
        run: echo "Repo = $GITHUB_ACTION_REPOSITORY | Actions = $GITHUB_ACTIONS | Actor = $GITHUB_ACTOR | ACtorId = $GITHUB_ACTOR_ID"
      - name: Print Organization Secret
        run: echo "My organization secret:${{ secrets.HELLO }}"
        env:
          First_Name: Mona
