name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      - name: "Print environment stuff"
        run: echo "Repo = $GITHUB_ACTION_REPOSITORY | Actions = $GITHUB_ACTIONS | Actor = $GITHUB_ACTOR | ACtorId = $GITHUB_ACTOR_ID"
      - name: "Print Codespace variable"
        run: echo "Codespace = ${{secrets.HELLO}} | Actions = $GITHUB_ACTIONS | Actor = $GITHUB_ACTOR | ACtorId = $GITHUB_ACTOR_ID"  
        env:
          First_Name: Mona
